### ISSUE TITLE
Realflight 9.5?

### ISSUE THREAD

**Issue by robustini** [Scavanger/INAV-SIM-OSD#1]
Thank you for this tool!
I can't get it to work with Realflight 9.5, is the Evolution version required?
"Unable to detect simulator", MSP Displayport configured on UART4.
All the features in SITL work, the model flies smoothly even with automatons.

**Comment by Scavanger** [comment]
It just didn't detect the RF 9.5 Window. 
Can you send me a Screenshot of the the task manager (Details page) with the name of the RealFlight process (not the window name), please?
![RF-Task-Manager](https://user-images.githubusercontent.com/1850465/231808798-ae897f83-96fa-4834-8ad0-2337cde4e835.png)

**Comment by robustini** [comment]
> 

The executable name is "Realflight.exe", checked in the path "Programs Files (x86)\Realflight9"

![immagine](https://user-images.githubusercontent.com/3864712/231825853-01ee9148-9d68-4dcc-95e3-1b686260c480.png)

**Comment by robustini** [comment]
Yes, solved by simply copying Realflight.exe to Realflight64.exe (and the related .ini) and it works.
So please look for both executables to make it compatible without this trick, thanks!

**Comment by robustini** [comment]
![immagine](https://user-images.githubusercontent.com/3864712/231827755-2999de74-df22-460d-a552-bda621509614.png)

**Comment by Scavanger** [comment]
Fixed in 0.2:
https://github.com/Scavanger/INAV-SIM-OSD/releases

**Comment by robustini** [comment]
> Fixed in 0.2: https://github.com/Scavanger/INAV-SIM-OSD/releases

Tested but it doesn't work, maybe my mistake, i'm sorry.
If the search for the name of the executable is case sensitive it is called "RealFlight.exe" and not "Realflight.exe", so with a capital F.

**Comment by robustini** [comment]
Sorry to make this request here but I don't know if you have a repo for Configurator with SITL as well.
It would be helpful if the order of the motors and servos could be saved in the SITL profile, every time I go back to it it goes back to the default and I have to change it manually.
This for example the correct order for the model I use, and the default is another.
"Serial to TCP" also always comes back enabled but I don't use it.

![immagine](https://user-images.githubusercontent.com/3864712/231960013-22657c08-2ba0-4ea5-82a8-0d53abfbd0ac.png)

**Comment by Scavanger** [comment]
Thanks, I will fix it.

For Configurator open an issue on the  inav Configurator Github page, it's now part in the official repro.
