### ISSUE TITLE
Build issue using MVSC Version 17.7.4

### ISSUE THREAD

**Issue by lida2003** [Scavanger/INAV-SIM-OSD#2]
Is there any guide or key points need to be pay special attention?

I got this build issue, since there is no discussion, I post an issue for help!

Hope to find the answer.

- build solution error:
![图片](https://github.com/Scavanger/INAV-SIM-OSD/assets/1296171/1fe7cf19-2c28-411f-aee9-01a1c5801e32)

- Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.7.4

![图片](https://github.com/Scavanger/INAV-SIM-OSD/assets/1296171/bf61a4a3-b860-486f-a0fb-3655a10e642c)

- git version

```
commit 8ac49edef6f20eca81ed7a3b9c8f19cc3b380e5a (HEAD -> master, tag: 0.2.1, origin/master, origin/HEAD)
Author: Andi Kanzler <andi_kanzler@gmx.de>
Date:   Fri Apr 14 18:02:10 2023 -0300

    Realflight 9.5 fix

```

**Comment by Scavanger** [comment]
See: https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3821?view=vs-2022

Better use Git to clone the Repro to avoid  these errors.
